In [1]:
import numpy as np

import numpy as np
a = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

problem 1

# To Solve the matrix product of A and B by hand

a. To find the matrix product of A and B, the number of columns of A should be equal to the number of columns in B

b. Multiplying each value in row in A by each value in column in B

A.B = {
(-1*0) + (2*0) + (3*2)     (-1*2) + (2*2) + (3*9)    (-1*1) + (2*8) + (3*-1)
(1*0) + (-5*0) + (6*2)     (4*2) + (-5*2) + (6*9)     (4*1) + (-5*-8) + (6*-1)
(7*0) + (8*0) + (-9*2)      (7*2) + (8*2) + (-9*9)     (7*1) + (8*-8) + (-9*-1)
}

A.B = {
0+0+6       -2+4+27     -1-16-3
0+0+12       8-10+27     4+40-6
0+0-18       14+16-81    7-64+9
}

A.B = {
6   29  -20
12  52   38
-18 -51  48
}

problem 2
:Calculation by NumPy function

In [6]:
matmul = np.matmul(a, b)

dot_product = np.dot(a, b)

at = a @ b

print("Using np.matmul: \n {}\n".format(matmul))

print("Using dot method: \n {}\n".format(dot_product))

print("Using @:\n {}".format(at))

Using np.matmul: 
 [[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]

Using dot method: 
 [[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]

Using @:
 [[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


problem 3
:Implementation of calculation of a certain element

In [8]:
result = []
c = b.T #tranposing b 
outer = 0
columns = a.shape[0] #each row of a multiplies each column of b

while outer < columns:
    inner = 0
    rows = c.shape[0] # number of columns in transposed b
    while inner < rows:
        result.append((a[outer] * c[inner]).sum())
        inner += 1
    outer += 1
#The shape of the new array is (row a, row b), this is due to the transpose in the ln 2
result = np.array(result).reshape((a.shape[0], c.shape[0])) 
print(result)

print("Verifying my solution by comparing output using numpy inbuilt function \n {}".format(result == a @ b))

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]
Verifying my solution by comparing output using numpy inbuilt function 
 [[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


problem 4:
Implementation of calculation of a certain element

In [20]:
#To Perform a matrix multiplication of a and b

import numpy as np

import numpy as np
a = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])


def mat_multiply(a, b):
    #Performs a matrix multiplication between a and b
    result = []
    b = b.T #tranposing b to make selection of column values easy
    outer = 0
    columns = a.shape[0]
    """The while loop runs (row a * row b.T) times, which is same
    as (row a * column b) times because each row of a multiplies each column of b"""
    while outer < columns:
        inner = 0
        rows = b.shape[0] # number of columns in transposed b
        while inner < rows:
            result.append((a[outer] * b[inner]).sum())
            inner += 1
        outer += 1
   #The transposition of b makes the shape of the new array different; (row a, row b) 
    result = np.array(result).reshape((a.shape[0], b.shape[0])) 
    return result
print(mat_multiply(a, b))

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


Problem 5: 
Creating a function that performs matrix multiplication 


In [17]:
def mat_multiply(a, b):
    """Performs a matrix multiplication between a and b"""
    result = []
    c = b.T #tranposing b to make selection of column values easy
    outer = 0
    columns = a.shape[0]
    """The while loop runs (row a * row b.T) times, which is same
    as (row a * column b) times because each row of a multiplies each column of b"""
    try:
        if a.shape[1] != b.shape[0]:
            raise ValueError
    except ValueError:
        
        print(f"Number of columns in A: {a.shape[1]} must be equal to number of rows in B: {b.shape[0]}")
    #The transposition of b makes the shape of the new array different; (row a, row b) 
    else:
        while outer < columns:
            inner = 0
            rows = c.shape[0] # number of columns in transposed b
            while inner < rows:
                result.append((a[outer] * c[inner]).sum())
                inner += 1
            outer += 1
        result = np.array(result).reshape((a.shape[0], b.shape[0])) 
        return result

test = np.random.randint(3, 10, (4, 6))

mat_multiply(a, test)

Number of columns in A: 3 must be equal to number of rows in B: 4


Problem 6:
Transposition
    

In [13]:
a = a.T
b = b.T

print(mat_multiply(a, b), "\n")

#Confirmation
print(mat_multiply(a, b) == a@b)


[[ 15 -48  27]
 [ -2 -74 -49]
 [  3  84  69]] 

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
