print(1+1)


print(1+2)

# Markdownとは

## ゴール
- **MarkDownとはなにかを理解し、記述できるようになる**

## Markdownとはなにか

Markdown（マークダウン）とは、文書を記述するためのマークアップ言語の1つです。
マークアップ言語とは、テキストを構造化するための言語のことです。タグや記号を使ってテキストに目印をつけることによって、人間だけでなくコンピュータでもテキストの構造を認識できるようにします。

身近なマークアップ言語の1つとしてHTMLがありますが、HTMLのマークアップはタグの種類も多く覚えるまでにある程度の時間を要します。それに対し、MarkdownはHTMLをさらに簡略化したマークアップ言語であることから、覚えやすく手軽に利用できます。

## なぜMarkdownを学ぶのか

Markdownは、元々テキスト形式で書いた文書からHTMLを生成するために開発されました。しかし、近年ではHTMLに留まらず、PDFやその他さまざまなファイル形式への変換にも対応しています。また、GitHubやStackOverFlowなど多くのサービスにおいてもMarkdownが採用されています。

Markdownはプログラミングに限らずさまざまな場面で利用されているため、是非この機会に身に付けておきましょう。ディープロにおいてもMarkdownが利用できる機能が豊富に用意されていますので、利用する際は積極的にMarkdownを活用しましょう。

In [10]:
sample text 2samplstext 2

SyntaxError: invalid decimal literal (2590558046.py, line 1)

In [ ]:
sample text 3  sample text 4


In [ ]:
sample text 3 
sample text 4

sample text 3 sample text 4


In [ ]:
sample text 1sample text 2


In [ ]:
sample text1
sample text2

In [ ]:
sample text 1 
sample text 2


In [ ]:
>sample

In [ ]:
m

In [ ]:
_my elie_

In [ ]:
** markdown **

In [ ]:
**markdown**

In [11]:
1. Apple
1. oranges
1.  vegetables
1. carrots

SyntaxError: invalid syntax (3730760620.py, line 1)

In [12]:
"@"

'@'

In [13]:
`<h1>Saple Code</h1>`

SyntaxError: invalid syntax (2713441802.py, line 1)

In [14]:
print(1+2)

3


print(1+2)

In [16]:
1. Fruits
1. Apple
1. Banana
1. Orange
1. Vegetables
1. tomato
1. potato
1. onion

SyntaxError: invalid syntax (4003210852.py, line 1)

1. Fruits
1. Apple
1. Banana
1. Orange
1. Vegetables
1. tomato
1. potato
1. onion

- Apple
- Banana
- Orange

> Sample5
Sample6
Sample7

> Sample1  
> Sample2

> Sample3
>> Sample4

# Title1
## Title2
### Title3
#### Title4
##### Title5
###### Title6

1.  Fruits
1. Apple
1. Banana
1. Orange
1.  Vegetables
1. tomato
1. potato
1. onion

1. Fruits
1. Apple
1. Banana
1. Orange

1. Vegetables
1. tomato
1. potato
1. onion

`<h1>Saple Code</h1>`

To display the heading of a page in HTML, use the `<h1>` tag like this: `<h1>Heading</h1>

'<h1>'

'''
def add(n, y)
if n == 0
return n
end
n + y
end
puts add(0, 3)
'''

'''
def add (n,y)
  if n==0
  end
  n+y
  end
put add (o, 31)
'''

In [17]:
''' def add (n,y) if n==0 end n+y end put add (o, 31) '''

' def add (n,y) if n==0 end n+y end put add (o, 31) '

''' def add (n,y) if n==0 end n+y end put add (o, 31) '''

In [18]:
10/0

ZeroDivisionError: division by zero

In [1]:
print(20+30+50)

100


In [1]:
print(type(7*9))

<class 'int'>


In [2]:
print(type(5/2))

<class 'float'>


In [3]:
print(type(john))

NameError: name 'john' is not defined

In [4]:
print(50/2)

25.0


In [5]:
print(type(50/2))

<class 'float'>


In [6]:
print(2.0)
print(2.)
print(0.5)
print(.5)

2.0
2.0
0.5
0.5


In [7]:
print(float(4))

4.0


In [8]:
print(int(3.9))

3


In [9]:
print(int(3.0))

3


In [10]:
print(int(0.9))

0


In [11]:
print(float(2.0))

2.0


In [12]:
print(type(float(2.0)))

<class 'float'>


In [13]:
print(float(2.0))
print(type(float(2.0)))

2.0
<class 'float'>


In [14]:
print(3 + 5*4 - 10/2)

18.0


In [15]:
print( 5*4 3 +- 10/2)

SyntaxError: invalid syntax. Perhaps you forgot a comma? (3065163523.py, line 1)

In [16]:
( 5*4 3 + 10/2)

SyntaxError: invalid syntax. Perhaps you forgot a comma? (2811229388.py, line 1)

In [17]:
( 5*4+3-10/2)

18.0

In [1]:
x = 250 + 100 + 400
print(x)

750


In [1]:
y = x/2
print(y)

NameError: name 'x' is not defined

In [2]:
x = 250 + 100 + 400
print(x)

750


In [3]:
y = x/2
print(y)

375.0


In [4]:
print(x*2)

1500


In [5]:
print(type(x))
print(type(y))

<class 'int'>
<class 'float'>


In [6]:
s, t = 100, 200
print(s+t)

300


In [7]:
print(type(s))
print(type(t))

<class 'int'>
<class 'int'>


In [8]:
reserved word

SyntaxError: invalid syntax (3424265594.py, line 1)

In [9]:
print = 100
print("Hello, World!")

TypeError: 'int' object is not callable

In [10]:
x = 1
x = x + 5
print(x)

TypeError: 'int' object is not callable

In [11]:
x=1
x+=5
print(x)

TypeError: 'int' object is not callable

In [12]:
x=1
x+=5
print(x)

TypeError: 'int' object is not callable

In [13]:
x = 250 + 100 + 400
print(x)

TypeError: 'int' object is not callable

In [1]:
x = 250 + 100 + 400
print(x)

750


In [2]:
x = 1
x = x + 5
print(x)

6


In [3]:
x = 1
x += 5
print(x)

6


In [1]:
print("text")

text


In [2]:
print(type("text"))

<class 'str'>


In [3]:
print(Elie)

NameError: name 'Elie' is not defined

In [4]:
print(""Elie""")

SyntaxError: unterminated triple-quoted string literal (detected at line 1) (775541862.py, line 1)

In [5]:
nt(""Elie""pri

SyntaxError: invalid syntax. Perhaps you forgot a comma? (1201013007.py, line 1)

In [6]:
print(""Elie"")

SyntaxError: invalid syntax. Perhaps you forgot a comma? (3081528837.py, line 1)

In [7]:
print("Elie")

Elie


In [8]:
print("learn python")
print("Hello")

learn python
Hello


In [9]:
student_name = "Alice"
print(student_name)

Alice


In [10]:
print("Hello world")

Hello world


In [11]:
Name=Elie
print("I am")+ Elie

NameError: name 'Elie' is not defined

In [12]:
Name="Elie"
print("I am")+ "Elie"

I am


TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

In [13]:
Name="Elie"
print("I am")+( "Elie") 

I am


TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

In [14]:
Name="Elie"
print("I am"+"Elie") 

I amElie


In [15]:
Name="Elie"
print("I am" + "Elie")

I amElie


In [16]:
Name="Elie"
print("I am" + "Elie") 

I amElie


In [17]:
student_name = "Alice"
print("my name is" + student_name + "!!")

my name isAlice!!


In [18]:
student_name = "Alice"
print("my name is" +   student_name + "!!")

my name isAlice!!


In [19]:
Name="Elie"
print("I am"   +   "Elie")

I amElie


In [20]:
student_age = 19
print("My age is" + str(student_age) + "!!")

My age is19!!


In [21]:
Name="Elie"
print(("I am") + ("Elie")) 

I amElie


In [22]:
Name="Elie"
print("I am"  +  "Elie") 

I amElie


In [23]:
Name="Elie"
print("I am"   + "Elie") 

I amElie


In [24]:
Name="Elie"
print("I am " + "Elie") 

I am Elie


In [25]:
student_age = 19
print("My age is " + str(student_age) + "!!")

My age is 19!!


In [1]:
Student_name= Alice
print("my name is{}!!".format(student_name)

SyntaxError: incomplete input (392542215.py, line 2)

In [2]:
Student_name = "Alice"
print("my name is{}!!".format(student_name))

NameError: name 'Alice' is not defined

In [3]:
Student_name = "Alice"
print("my name is{}!!".format(student_name))

NameError: name 'student_name' is not defined

In [4]:
("my name is{}!!".format(student_name))

NameError: name 'student_name' is not defined

In [5]:
student_name = "Alice"
print("my name is{}!!".format(student_name))

my name isAlice!!


In [6]:
Student_name = "Alice"
print("my name is{}!!".format(student_name))

my name isAlice!!


In [8]:
Student_name = "Alice"
print("my name is {}!! ".format(student_name))

my name is Alice!! 


In [9]:
student_name = "Alice"
student_age = 19
print("my name is {} !!".format (student_name, student_age))

my name is Alice !!


In [10]:
student_name = "Alice"
student_age = 19
print("my name is{}で、{}歳!!".format(student_name, student_age))

my name isAliceで、19歳!!


In [11]:
student_name = "Alice"
student_age = 19
print("my name is, i am {} !!".format (student_name, student_age))

my name is, i am Alice !!


In [12]:
student_name = "Alice"
student_age = 19
print("my name is, {} I am !!".format (student_name, student_age))

my name is, Alice I am !!


In [13]:
student_name = "Alice"
student_age = 19
print("my name is{}で、{}歳!!".format(student_name, student_age))

my name isAlice I 19 am !!


In [14]:
student_name = "Alice"
student_age = 19
print("my name is{}I am {} !!".format(student_name, student_age))

my name isAliceI am 19 !!


In [15]:
student_name = "Alice"
student_age = 19
print("My name is, {} I am {} !!" .format (student_name, student_age))

My name is, Alice I am 19 !!


In [16]:
student_name = "Alice"
student_age = 19
print("My name is, {}. I am {} !!" .format (student_name, student_age))

My name is, Alice. I am 19 !!


In [17]:
student_name = "Alice"
student_age = 19
print("My name is, {}. I am {} " .format (student_name, student_age) "years old. !!")

SyntaxError: invalid syntax. Perhaps you forgot a comma? (4006096715.py, line 3)

In [18]:
student_name = "Alice"
student_age = 19
print("My name is, {}. I am {} "years old. !!" .format (student_name, student_age) )

SyntaxError: unterminated string literal (detected at line 3) (4247856596.py, line 3)

In [19]:
student_name = "Alice"
student_age = 19
print("My name is, {}. I am {} years old." .format (student_name, student_age))

My name is, Alice. I am 19 years old.


In [1]:
Weather_text= "sunny"
print("Today's weather is {}!!")

Today's weather is {}!!


In [2]:
Weather_text= "sunny"
= "sunny"("Today's weather is {}!!" .format (Weather_text))

Today's weather is sunny!!


In [3]:
Weather_text="Today's weather is {}!!"
Weather_text= "sunny"
 print(Weather_text)

IndentationError: unexpected indent (504401262.py, line 3)

In [4]:
Weather_text="Today's weather is {}!!"
Weather_text= "sunny.format("Sunny")"
 print(Weather_text.format("Sunny")

SyntaxError: invalid syntax (14825670.py, line 2)

In [6]:
Weather_text="Today's weather is {}!!"
Weather_text= .format("Sunny")"
 print(Weather_text)

SyntaxError: unterminated string literal (detected at line 2) (1624492658.py, line 2)

In [8]:
Weather_text="Today's weather is {}!!"
Weather_text=Weather.format("Sunny")
print(Weather_text)

NameError: name 'Weather' is not defined

In [9]:
Weather_text="Today's weather is {}!!"
Weather_text=Weather_text.format("Sunny")
print(Weather_text)

Today's weather is Sunny!!


In [10]:
today_temperature= 3
tomorrow_temperature=-5
print ("Today's lowest temperature is{:+} and tomorrow's lowest temperature is {:+}

SyntaxError: unterminated string literal (detected at line 1) (472560767.py, line 1)

In [11]:
today_temperature= 3
tomorrow_temperature=-5
print ("Today's lowest temperature is{:+} and tomorrow's lowest temperature is {:+}

SyntaxError: unterminated string literal (detected at line 3) (2007968358.py, line 3)

In [12]:
today_temperature = 3
tomorrow_temperature = -5
print("Today's lowest temperature is {:+} and tomorrow's lowest

SyntaxError: unterminated string literal (detected at line 3) (1658097697.py, line 3)

In [13]:
today_temperature = 3
tomorrow_temperature = -5
print("Today's lowest temperature is {:+} and tomorrow's lowest".format(today_temperature, tomorrow_temperature))

Today's lowest temperature is +3 and tomorrow's lowest


In [16]:
today_temperature = 3
tomorrow_temperature = -5
print("Today's lowest temperature is {:+}  and tomorrow's lowest is {:+}".format(today_temperature, tomorrow_temperature))

Today's lowest temperature is +3  and tomorrow's lowest is -5


In [3]:
today_temperature= 3.35
tomorrow_temperature= -5.75
print("today's temperature is {:.1f} and tomorroow's temperature is {:.1f}".format(today_temperature,tomorrow_temperature))

today's temperature is 3.4 and tomorroow's temperature is -5.8


In [19]:
today_temperature= 3.35
tomorrow_temperature= -5.75
print("today's temperature is {1+:.1f} and tomorroow's temperature is {0:+.1f}".format(today_temperature,tomorrow_temperature))

KeyError: '1+'

In [20]:
today_temperature= 3.35
tomorrow_temperature= -5.75
print("tomorrow's lowest temperature is {1:+.1f} and today's lowest temperature is {0:+.1f}".format(today_temperature,tomorrow_temperature))

tomorrow's lowest temperature is -5.8 and today's lowest temperature is +3.4


In [21]:
print("python".capitalize())

Python


In [22]:
student_age = 13
print("student age is", (student age))

SyntaxError: invalid syntax. Perhaps you forgot a comma? (4256304651.py, line 2)

In [23]:
student_age = 13
print("student age is", studentage)

SyntaxError: invalid syntax. Perhaps you forgot a comma? (741528951.py, line 2)

In [24]:
student_age = 13
print("student age is", (student_age))

student age is 13


In [25]:
student_age= 19
print("student age is",student_age, sep =":")

student age is:19


In [26]:
print(*objects, sep=' ', end='\n', file=sys.stdout, flush=False)

NameError: name 'objects' is not defined

In [28]:
january_average_temperature= 30
february_average_temperature= 40
print("average temperature for january is {} and average temperature for february is {}".format(january_average_temperature, february_average_temperature))

average temperature for january is 30 and average temperature for february is 40


In [38]:
january_average_temperature= 30
february_average_temperature= 40
print("average temperature for january is " + str (january_average_temperature), "and average temperature for february is "  + str (february_average_temperature))

average temperature for january is 30 and average temperature for february is 40


In [40]:
monthly_average_temperature=[1, 2, 3, 4, 5, 6 ,7]
print(monthly_average_temperature)

[1, 2, 3, 4, 5, 6, 7]


In [41]:
monthly_average_temperature=[1, 2, 3, 4, 5, 6 ,7]
print(type (monthly_average_temperature))

<class 'list'>


In [49]:
monthly_average_temperature = [6, 7, 9, 15, 20, 22, 27, 26, 23, 17, 12, 7]
print("monthly average temperature for january is {} degrees and monthly average temperature for february is {} degrees".format(monthly_average_temperature[0], monthly_average_temperature [1])) 


monthly average temperature for january is 6 degrees and monthly average temperature for february is 7 degrees


In [46]:
monthly_average_temperatures = [6, 7, 9, 15, 20, 22, 27, 26, 23, 17, 12, 7]
print("The average temperature for each month is {} degrees in January and {} degrees in February!!".format(monthly_average_temperatures[0], monthly_average_temperatures[1]))

The average temperature for each month is 6 degrees in January and 7 degrees in February!!


In [51]:
monthly_average_temperature = [6, 7, 9, 15, 20, 22, 27, 26, 23, 17, 12, 7]
print("monthly average temperature for july is {} degrees and monthly average temperature for december is {} degrees".format(monthly_average_temperature[6], monthly_average_temperature [11]))

monthly average temperature for july is 27 degrees and monthly average temperature for december is 7 degrees


In [1]:
print(monthly_average_temperatures[5])
monthly_average_temperatures[5] = 24
print(monthly_average_temperatures[5])

NameError: name 'monthly_average_temperatures' is not defined

In [2]:
print(monthly_average_temperatures[5])
monthly_average_temperatures[5] = 24
print(monthly_average_temperatures[5])

NameError: name 'monthly_average_temperatures' is not defined

In [1]:
monthly_average_temperatures[5] = 24
print(monthly_average_temperatures[5])
print(monthly_average_temperatures[5])

NameError: name 'monthly_average_temperatures' is not defined

In [3]:
monthly_average_temperatures = [6, 7, 9, 15, 20, 22, 27, 26, 23, 17, 12, 7]
print(monthly_average_temperatures[5])
monthly_average_temperatures[5] = 24
print(monthly_average_temperatures[5])

22
24


In [4]:
monthly_average_temperatures = [6, 7, 9, 15, 20, 22, 27, 26, 23, 17, 12, 7]
print(monthly_average_temperatures[0:7:2])

[6, 9, 20, 27]


In [5]:
monthly_average_temperatures = [6, 7, 9, 15, 20, 22, 27, 26, 23, 17, 12, 7]
print(monthly_average_temperatures[0:7:2])

[6, 9, 20, 27]


In [6]:
monthly_average_temperatures = [6, 7, 9, 15, 20, 22, 27, 26, 23, 17, 12, 7]
print(monthly_average_temperatures[::5])

[6, 22, 12]


In [4]:
monthly_average_temperatures = [6, 7, 9, 15, 20, 22, 27, 26, 23, 17, 12, 7]
print(monthly_average_temperatures[::-1])

[7, 12, 17, 23, 26, 27, 22, 20, 15, 9, 7, 6]


In [8]:
monthly_average_temperatures = [6, 7, 9, 15, 20, 22, 27, 26, 23, 17, 12, 7]
print(len(monthly_average_temperatures))

12


In [1]:
THICKNESS = 0.00008

folded_thickness = THICKNESS * 2

print("Thickness: {} meters

Thickness: 0.00016 meters


In [2]:
print("Thickness: {0+:.2f} kilometers".format(folded_thickness / 1000))

Thickness:  0.00 kilometers


In [5]:
folded_thickness=0.00016
print("Thickness: {0+:.2f} kilometers".format(folded_thickness / 1000))

KeyError: '0+'

In [9]:
folded_thickness=0.00016 
print("Thickness: {: .2f} kilometers".format(folded_thickness / 1000))

Thickness:  0.000 kilometers


In [10]:
folded_thickness=0.00016 
print("Thickness: {: .3f} kilometers".format(folded_thickness / 1000))

Thickness:  0.000 kilometers


In [11]:
folded_thickness=0.00016 
print("Thickness: {: .4f} kilometers".format(folded_thickness / 1000))

Thickness:  0.0000 kilometers


In [12]:
folded_thickness=0.00016 
print("Thickness: {: .8f} kilometers".format(folded_thickness / 1000))

Thickness:  0.00000016 kilometers


In [13]:
folded_thickness=0.00016 
print("Thickness: {: .7f} kilometers".format(folded_thickness / 1000))

Thickness:  0.0000002 kilometers


In [14]:
Name = "Tom"
age = 15

if age > 18:
    print("Tom is an Adult")
else:
    print("{} is not an adult yet".format(Name))
       

Tom is not an adult yet


In [21]:
Name = "Tayo"
Age = 29
if Age > 30:
    print("{} Is over the age to serve".format(Name))
    
else:
     print("{} is eligeable to serve".format(Name))

Tayo is eligeable to serve


In [22]:
Name_of_Students = ("Temi", "Tayo", "ELsa")
Name_of_Student1,Name_of_Student2,Name_of_Student3 =  Name_of_Students  
print(Name_of_Student1,Name_of_Student2)


Temi Tayo


In [36]:
Name_of_Students = ("Temi", "Tayo", "ELsa")
Age_of_Students = (20, 34, 33)

Name_of_Student1,Name_of_Student2,Name_of_Student3 =  Name_of_Students  
Age_Name_of_Student1,Age_Name_of_Student2,Age_Name_of_Student3= Age_of_Students   


if Age_Name_of_Student1 <= 30:
    print("{} is eligible to serve".format(Name_of_Student1))
if Age_Name_of_Student2 <= 30:
    print("{} is eligible to serve".format(Name_of_Student2))
if Age_Name_of_Student3 <= 30:
    print("{} is eligible to serve".format(Name_of_Student3))
else:
    print("{} is not eligible to serve".format(Name_of_Students))

Temi is eligible to serve
('Temi', 'Tayo', 'ELsa') is not eligible to serve


In [37]:
Name_of_Students = ("Temi", "Tayo", "ELsa")
Age_of_Students = (20, 34, 33)

eligible_students = []
ineligible_students = []

for name, age in zip(Name_of_Students, Age_of_Students):
    if age <= 30:
        eligible_students.append(name)
    else:
        ineligible_students.append(name)

if eligible_students:
    print("Eligible to serve:", ", ".join(eligible_students))
if ineligible_students:
    print("Not eligible to serve:", ", ".join(ineligible_students))

Eligible to serve: Temi
Not eligible to serve: Tayo, ELsa


In [39]:
Name_of_Students = ("Temi", "Tayo", "ELsa")
Age_of_Students = (20, 34, 33)

eligible_students = []
ineligible_students = []

for name, age in zip(Name_of_Students, Age_of_Students):
    if age <= 30:
        eligible_students.append(name)
    else:
        ineligible_students.append(name)

if eligible_students:
    print("{} is eligible to serve".format(Name_of_Students))
if ineligible_students:
    print("{} is ineligible to serve".format(Name_of_Students))

('Temi', 'Tayo', 'ELsa') is eligible to serve
('Temi', 'Tayo', 'ELsa') is ineligible to serve


In [1]:
Weather_text= "Today's weather is sunny"
print("weather_text")

weather_text


In [2]:
weather_text= "today's weather is" 
weather_text = weather_text. format "sunny"

SyntaxError: invalid syntax (1936124116.py, line 2)

In [4]:
print("Elie")

Elie


In [2]:
print("Elie")

Elie


In [6]:
name= "elie"
print(name)

elie


In [1]:
s,t= 2, 5
y= s+t
print (y)

7


In [9]:
name ="ELIE"
print( "my name is {}" .format(name))

my name is ELIE


In [14]:
sex ="female"
print( "i am {}" .format(sex))

i am female


In [16]:
January_average_temperature=7
February_average_temperature=9
print("Average temperature for January is {}, and Average temperature for February is {}" .format(January_average_temperature, February_average_temperature))

Average temperature for January is 7, and Average temperature for February is 9


In [17]:
Monthly_average_temperature= [1, 2, 3, 4, 5, 6, 7, 8, 9, 12, 21, 11]
print("The monthly average temperature for April and July are, {} and {} degrees respectively" .format(Monthly_average_temperature[3], Monthly_average_temperature[6]))

The monthly average temperature for April and July are, 4 and 7 degrees respectively


In [18]:
print(Monthly_average_temperature[5])

6


In [19]:
print(Monthly_average_temperature[2:7])

[3, 4, 5, 6, 7]


In [20]:
print(Monthly_average_temperature[2:7:3])

[3, 6]


In [21]:
print(Monthly_average_temperature[6:2:-3])

[7, 4]


In [26]:
numbers = [0, 1, 2, 3]
numbers.append(4)
print(numbers)

[0, 1, 2, 3, 4]


In [35]:
text = [ "Benz, camry, rg"]
text.append("mecedes")
print(text)

['Benz, camry, rg', 'mecedes']


In [29]:
numbers = [5, 6, 7]
numbers.append(8)
print(numbers)

[5, 6, 7, 8]


In [36]:
numbers = [0, 1, 2, 3]
print(numbers.append(4))
print(numbers)

None
[0, 1, 2, 3, 4]


In [39]:
text = "python"
text.capitalize()
text_capitalized = text.capitalize()
print(text)
print(text_capitalized)

python
Python


In [38]:
text = "python"
text.capitalize()
print(text)
capitalized_text = text.capitalize()
print(text)
print(capitalized_text)

python
python
Python


In [40]:
Id_numbers= ("A128", "A556", "A939")
print(Id_numbers)

('A128', 'A556', 'A939')


In [41]:
print(type(Id_numbers))

<class 'tuple'>


In [44]:
print(Id_numbers[1])

A556


In [45]:
user_ids = ["A081", "A114", "A186"]
print(user_ids)
print(type(user_ids))
user_ids[0] = "A082"
print(user_ids)

['A081', 'A114', 'A186']
<class 'list'>
['A082', 'A114', 'A186']


In [46]:
user_ids = "A081", "A114", "A186"
print(user_ids)

('A081', 'A114', 'A186')


In [1]:
s, t = 100, 200
print(s+t)

300


In [2]:
(s, t) = (100, 200)
print(s+t)

300


In [3]:
user_ids = ("A081", "A114", "A186")
user_id1, user_id2, user_id3 = user_ids
print(print(user_ids))

('A081', 'A114', 'A186')
None


In [5]:
user_ids = ("A081", "A114", "A186")
user_id1, user_id2, user_id3 = user_ids
print(user_id1, user_id2)

A081 A114


In [8]:
user_ids = ("A081", "A114", "A186")
print(user_ids)
print(list(user_ids))

('A081', 'A114', 'A186')
['A081', 'A114', 'A186']


In [9]:
user_ids = ("A081", "A114", "A186")
print(user_ids)
print(list(user_ids))

('A081', 'A114', 'A186')
['A081', 'A114', 'A186']


In [11]:
student_name ="Elie"
student_age= 19
if student_age <20:
 print("{} is below 20 years of Age".format(student_name))
else:
    print("{} is above 20 years of Age".format(student_name))

Elie is below 20 years of Age


In [12]:
student_name ="Elie"
student_age= 26
if student_age <20:
 print("{} is below 20 years of Age".format(student_name))
else:
    print("{} is above 20 years of Age".format(student_name))

Elie is above 20 years of Age


In [14]:
student_name ="Elie"
student_age= 22
if student_age <20:
 print("{} is below 20 years of Age".format(student_name))
elif student_age == 21:
 print("{} is 21 years old".format(student_name))
elif student_age == 22:
 print("{} is 22 years old".format(student_name))
else:   
  print("{} is above 23 years of Age".format(student_name))

Elie is 22 years old


In [15]:
student_name ="Elie"
student_age= 21
if student_age <20:
 print("{} is below 20 years of Age".format(student_name))
elif student_age == 21:
 print("{} is 21 years old".format(student_name))
elif student_age == 22:
 print("{} is 22 years old".format(student_name))
else:   
  print("{} is above 23 years of Age".format(student_name))

Elie is 21 years old


In [16]:
student_name ="Elie"
student_age= 13
if student_age <20:
 print("{} is below 20 years of Age".format(student_name))
elif student_age == 21:
 print("{} is 21 years old".format(student_name))
elif student_age == 22:
 print("{} is 22 years old".format(student_name))
else:   
  print("{} is above 23 years of Age".format(student_name))

Elie is below 20 years of Age


In [17]:
student_name ="Elie"
student_age= 23
if student_age <20:
 print("{} is below 20 years of Age".format(student_name))
elif student_age == 21:
 print("{} is 21 years old".format(student_name))
elif student_age == 22:
 print("{} is 22 years old".format(student_name))
else:   
  print("{} is above 23 years of Age".format(student_name))

Elie is above 23 years of Age


In [18]:
student_name ="Elie"
student_age= 28
if student_age <20:
 print("{} is below 20 years of Age".format(student_name))
elif student_age == 21:
 print("{} is 21 years old".format(student_name))
elif student_age == 22:
 print("{} is 22 years old".format(student_name))
else:   
  print("{} is above 23 years of Age".format(student_name))

Elie is above 23 years of Age


In [19]:
student_name = "Elie"
student_age = 22
if student_age < 20:
  print("{} is under 20 years old.".format(student_name))
elif student_age >= 21:
  print("{} Is over 21 years old.".format(student_name))
elif student_age == 22:
  print("{} is 22 years old.".format(student_name))

Elie Is over 21 years old.


In [23]:
print(19<20)
print(type(19<20))
print(22<20)
print(type(22<20))

True
<class 'bool'>
False
<class 'bool'>


In [33]:
if True: 
 print("Hello,Elie")

Hello,Elie


In [29]:
if True:
  print("Hello, Boolean!")

Hello, Boolean!


In [34]:
print(20 > 19.5)

True


In [35]:
print("Python" == "Python")

True


In [36]:
print("Python" == "Elie")

False


In [38]:
print("Python" != "Python")

False


In [40]:
student_name = "Elie"
student_age = 19
if (student_age >= 10) and (student_age < 20):
  print("{} is a teenager.".format(student_name))


Elie is a teenager.


In [41]:
student_name = "Elie"
student_age = 25
if (student_age >= 10) and (student_age < 20):
  print("{} is a teenager.".format(student_name))
else:   
  print("{} is an Adult".format(student_name))

Elie is an Adult


In [42]:
student_name = "Elie"
student_age = 21
if (student_age >= 15) or (student_age > 20):
  print("{} is over 15 or 20.".format(student_name))


Elie is over 15 or 20.


In [46]:
student_name = "Elie"
student_age = 12
if (student_age >= 15) or (student_age > 20):
  print("{} is over 15 or 20.".format(student_name))
else:   
  print("{} is below  15 years".format(student_name))

Elie is below  15 years


In [71]:
no_judgment = False
student_name = "Elie"
student_age = 19

if not(no_judgment):
    if student_age < 20:
        print("{} is below 20 years".format(student_name))
    else:
        print("{} is above 20 years".format(student_name))
else:
    print("age is not determined.")
 

Elie is below 20 years


In [61]:
no_judgement = False
student_name = "Alice"
student_age = 19

if not(no_judgement):
  if student_age < 20:
    print("{} is under 20 years old.".format(student_name))
  else:
    print("{} is over 20 years old.".format(student_name))
else:
  print("Age is not determined.")

Alice is under 20 years old.


In [72]:
no_judgment = False
student_name = "Elie"
student_age = 23

if not(no_judgment):
    if student_age < 20:
        print("{} is below 20 years".format(student_name))
    else:
        print("{} is above 20 years".format(student_name))
else:
    print("age is not determined.")

Elie is above 20 years


In [73]:
no_judgment = False
student_name = "Elie"
student_age = 0

if not(no_judgment):
    if student_age < 20:
        print("{} is below 20 years".format(student_name))
    else:
        print("{} is above 20 years".format(student_name))
else:
    print("age is not determined.")

Elie is below 20 years


In [74]:
no_judgment = False
student_name = "Elie"
student_age = 20

if not(no_judgment):
    if student_age < 20:
        print("{} is below 20 years".format(student_name))
    else:
        print("{} is above 20 years".format(student_name))
else:
    print("age is not determined.")

Elie is above 20 years


In [75]:
no_judgment = False
student_name = "Elie"
student_age = -19

if not(no_judgment):
    if student_age < 20:
        print("{} is below 20 years".format(student_name))
    else:
        print("{} is above 20 years".format(student_name))
else:
    print("age is not determined.")

Elie is below 20 years


In [76]:
no_judgment = False
student_name = "Elie"
student_age = 19

if not no_judgment:
    if student_age < 20:
        print("{} is below 20 years".format(student_name))
    else:
        print("{} is above 20 years".format(student_name))
else:
    print("age is not determined.")

Elie is below 20 years


In [1]:
ADULT_AGE= 20

student_name = "Elie"
student_age = 15
if (student_age > ADULT_AGE):
  print("{} is under the age of {}.".format(student_name, ADULT_AGE))
else:
    print("{} is above the age of {}".format(student_name, ADULT_AGE))

Elie is above the age of 20


In [3]:
numbers = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9,]
for number in numbers:
    print(number)

0
1
2
3
4
5
6
7
8
9


In [4]:
numbers = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9,]
for num in numbers:
    print(num)

0
1
2
3
4
5
6
7
8
9


In [5]:
user_ids = ("A081", "A114", "A186")
for user_id in user_ids: 
     print(user_id)  

A081
A114
A186


In [6]:
text = "Python"
for character in text:
  print(character)

P
y
t
h
o
n


In [7]:
snacks= ("cookies", "buns", "puff")
for snack in snacks:
    print(snack)

cookies
buns
puff


In [8]:
for i in range(10):
 print(i)


0
1
2
3
4
5
6
7
8
9


In [10]:
print (range(10))
print(list(range(10)))

range(0, 10)
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [11]:
print (range(12))
print(list(range(12)))

range(0, 12)
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]


In [12]:
for i in range(5, 10):
  print(i)

5
6
7
8
9


In [13]:
for i in range(5, 10, 2):
  print(i)

5
7
9


In [14]:
for i in range(9, -1, -1):
  print(i)

9
8
7
6
5
4
3
2
1
0


In [16]:
for i in range(12, -1, -1,):
   print(i)  

12
11
10
9
8
7
6
5
4
3
2
1
0


In [17]:
for i in reversed (range(10)):
   print(i)  

9
8
7
6
5
4
3
2
1
0


In [22]:
monthly_average_temperatures = [6, 7, 9, 15, 20, 22, 27, 26, 23, 17, 12, 7]
for i in range(len(monthly_average_temperatures)):
 print("the average monthly temperature is {}".format(i+1, monthly_average_temperatures ))

the average monthly temperature is 1
the average monthly temperature is 2
the average monthly temperature is 3
the average monthly temperature is 4
the average monthly temperature is 5
the average monthly temperature is 6
the average monthly temperature is 7
the average monthly temperature is 8
the average monthly temperature is 9
the average monthly temperature is 10
the average monthly temperature is 11
the average monthly temperature is 12


In [23]:
monthly_average_temperatures = [6, 7, 9, 15, 20, 22, 27, 26, 23, 17, 12, 7]
for i in range(len(monthly_average_temperatures)):
  print("The average monthly temperature is {} degrees.".format(i+1, monthly_average_temperatures[i]))

The average monthly temperature is 1 degrees.
The average monthly temperature is 2 degrees.
The average monthly temperature is 3 degrees.
The average monthly temperature is 4 degrees.
The average monthly temperature is 5 degrees.
The average monthly temperature is 6 degrees.
The average monthly temperature is 7 degrees.
The average monthly temperature is 8 degrees.
The average monthly temperature is 9 degrees.
The average monthly temperature is 10 degrees.
The average monthly temperature is 11 degrees.
The average monthly temperature is 12 degrees.


In [26]:
monthly_average_temperatures = [6, 7, 9, 15, 20, 22, 27, 26, 23, 17, 12, 7]
for i, temperature in enumerate(monthly_average_temperatures):
 print("The monthly average temperature is {} degrees.".format(i+1, temperature))

The monthly average temperature is 1 degrees.
The monthly average temperature is 2 degrees.
The monthly average temperature is 3 degrees.
The monthly average temperature is 4 degrees.
The monthly average temperature is 5 degrees.
The monthly average temperature is 6 degrees.
The monthly average temperature is 7 degrees.
The monthly average temperature is 8 degrees.
The monthly average temperature is 9 degrees.
The monthly average temperature is 10 degrees.
The monthly average temperature is 11 degrees.
The monthly average temperature is 12 degrees.


In [27]:
MONTH_NUMBERS = list(range(1,13))

monthly_average_temperatures = [6, 7, 9, 15, 20, 22, 27, 26, 23, 17, 12, 7]
for month_number, temperatures in zip(MONTH_NUMBERS,monthly_average_temperatures):
    print("The monthly average temperature is{} degrees.".format(month_number,temperature ))

The monthly average temperature is1 degrees.
The monthly average temperature is2 degrees.
The monthly average temperature is3 degrees.
The monthly average temperature is4 degrees.
The monthly average temperature is5 degrees.
The monthly average temperature is6 degrees.
The monthly average temperature is7 degrees.
The monthly average temperature is8 degrees.
The monthly average temperature is9 degrees.
The monthly average temperature is10 degrees.
The monthly average temperature is11 degrees.
The monthly average temperature is12 degrees.


In [28]:
num = 0
while num < 10:
  print(num)
  num += 3

0
3
6
9


In [30]:
def print_hello_world():
    print("hello, world")

In [32]:
 print_hello_world()

hello, world


In [1]:
def print_Hi_Elie():
    print("Hi, Elie !")

In [3]:
print_Hi_Elie()

Hi, Elie !


In [9]:
def print_hello_something(something):
    print("hello, {} !".format(something))
    
print_hello_something("python")

hello, python !


In [10]:
print_hello_something("python")

hello, python !


In [11]:
def print_hello_something (something):
    print("hello, {} !",format(something))
    
print_hello_something("python")

hello, {} ! python


In [12]:
print_hello_something("python")

hello, {} ! python


In [17]:
def print_hi_something(something):
    print("hi, {}!".format(something))

print_hi_something("Elie")

hi, Elie!


In [18]:
def print_hi_something(something):
    print("hi, {}!".format(something))

    print_hi_something("Elie")

In [22]:
def print_hi_something(something, end):
    print("hi, {}{}".format(something, end))

print_hi_something("Elie", "?")

hi, Elie?


In [27]:
def print_hi_something_how_are_you(something, end = "!"):
    print("hi, {} how are you{}".format(something, end))
    
print_hi_something_how_are_you("Elie")
print_hi_something_how_are_you("Elie", end = "?") 

hi, Elie how are you!
hi, Elie how are you?


In [28]:
def print_hi_something_how_are_you(something, end = "!"):
    return "hi, {} how are you{}".format(something, end)

print_hi_something_how_are_you("Elie", end = "!!")    

'hi, Elie how are you!!'

In [34]:
def sample_function(x, y):
 answer = ((x+y)*2)
 return answer 

print(sample_function(10,5))
print(sample_function(3,4))
print(sample_function(-20,-10))      

30
14
-60


In [35]:
ADULT_AGE = 20 # Adult age

def text_adult_age(personal_age, adult_age = 20):
  """
  Returns a string indicating whether or not you are over the adult age.

  Parameters:
  ------------
  personal_age : int
    Age of the person you want to judge
  adult_age : int (default : 20)
    Adult age. 20 years old by default.

  Returns:
  ------------
  str
    string greater than or equal to adult_age and less than
  """
  if personal_age > adult_age:
    return "Over the age of {}".format(adult_age)
  else:
    return "Under the age of {}".format(adult_age)

# Student information
student_name = "Alice"
student_age = 19

print("{} is {}".format(student_name, text_adult_age(student_age, adult_age = ADULT_AGE)))

Alice is Under the age of 20


In [1]:
# Code to calculate the thickness when the paper is folded once

THICKNESS = 0.00008

folded_thickness = THICKNESS * 2

print("Thickness: {} meters".format(folded_thickness))

Thickness: 0.00016 meters


In [2]:
import time
import matplotlib.pyplot as plt
# Code to calculate the thickness when the paper is folded once

def paperFold(numOfFolds):
    THICKNESS = 0.00008

    folded_thickness = THICKNESS * (2**43)

    print(f"Thickness: {round(folded_thickness/1000, 2)} Km")


def paperFoldLoop(numOfFolds):
    THICKNESS = 8e-5
    operand = 1
    for x in range(numOfFolds):
        operand *= 2
    folded_thickness = THICKNESS * operand
    print(f"Thickness: {round(folded_thickness/1000, 2)} Km")

In [3]:
# Convert meters to kilometers and display with two decimal places
print("Thickness: {: .2f} kilometers".format(folded_thickness / 1000))

Thickness:  0.00 kilometers


In [4]:
import time 
import matplorlib.pyplot as plt
# code to calculate the thickness when the paper is folded once

def paperfold(numOfFolds):
    THICKNESS = 0.00008
    operand = 1
    for x in range (numOfFolds):
        folded_thickness= THICKNESS*operand
        print(f"thickness:{round(folded_thickness/1000, 2)} km")

ModuleNotFoundError: No module named 'matplorlib'

In [5]:
python -m pip install -U pip
python -m pip install -U matplotlib

SyntaxError: invalid syntax (2825935170.py, line 1)

In [4]:
import numpy as np

a= np.array ([1,2,3])
a

array([1, 2, 3])

In [3]:
import numpy as np

a= np.array ([1,2,3])
print (a)

[1 2 3]


In [7]:
type(a)

numpy.ndarray

In [8]:
a.shape

(3,)

In [9]:
a.ndim

1

In [15]:
b=np.array([[1, 2, 3], [4, 5, 6]])

In [16]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
print(b)

[[1 2 3]
 [4 5 6]]


In [19]:
b.shape


(2, 3)

In [20]:
b.ndim

2

In [22]:
a = np.array([1, 2, 3])
b = np.array([[1, 2, 3], [4, 5, 6]])

In [24]:
a[0]

1

In [25]:
a[2]

3

In [27]:
a[-1]

3

In [28]:
b[-1]

array([4, 5, 6])

In [29]:
b[1, -1]

6

In [31]:
b[1, 0]

4

In [32]:
b[0,0]

1

In [33]:
b[0, -1]

3

In [34]:
a,b[[0, 1], [1, 0]]

(array([1, 2, 3]), array([2, 4]))

In [4]:
a = np.array([1, 2, 3])
b = np.array([[1, 2, 3], [4, 5, 6]])


In [5]:
a[1:]

array([2, 3])

In [6]:
a[0:]

array([1, 2, 3])

In [7]:
a[2:]

array([3])

In [8]:
b[1, :]

array([4, 5, 6])

In [9]:
b[0:]

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
b[0, :]

array([1, 2, 3])

In [11]:
a[0]= 7

In [12]:
a

array([7, 2, 3])

In [13]:
b[:2]=7

In [14]:
b

array([[7, 7, 7],
       [7, 7, 7]])

In [16]:
b[0,1 ]=6

In [17]:
b

array([[7, 6, 7],
       [7, 7, 7]])

In [18]:
b[:, 2]= 6

In [19]:
b

array([[7, 6, 6],
       [7, 7, 6]])

In [20]:
b[:, 2]= 6
print(b)

[[7 6 6]
 [7 7 6]]
